language: php
php:
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer validate

install:
  - composer install --ignore-platform-reqs --no-suggest

script:
  - security-checker security:check

cache:
  directories:
  - $HOME/.composer/cache
