language: php
php:
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer validate

install:
  - composer install --ignore-platform-reqs --no-suggest
  - export COMPOSER_BIN_DIR=$TRAVIS_BUILD_DIR/vendor/bin
  - export PATH=$COMPOSER_BIN_DIR:$PATH

script:
  - security-checker security:check --end-point=http://security.sensiolabs.org/check_lock

cache:
  directories:
  - $HOME/.composer/cache
