language: php
php:
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer validate

install:
  - composer install --ignore-platform-reqs

cache:
  directories:
  - $HOME/.composer/cache
